disabled_rules:
- line_length
- trailing_whitespace
- orphaned_doc_comment
- nesting
- todo

included:
- Projects/
excluded:
- Tuist/
- Projects/DesignSystem/Project.swift
- Projects/Data/Project.swift

identifier_name:
  excluded:
    - id
    - x
    - y
